force-app/main/default/objects/Element__c/Element__c.object-meta.xml
<CustomObject>
    <label>Element</label>
    <nameField>
        <label>Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mine__c/Mine__c.object-meta.xml
<CustomObject>
    <label>Mine</label>
    <nameField>
        <label>Mine Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mine__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <scale>3</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Mine__c/fields/Ore__c.field-meta.xml
<CustomField>
    <fullName>Ore__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ore</label>
    <referenceTo>Ore__c</referenceTo>
    <relationshipLabel>Mines</relationshipLabel>
    <relationshipName>Mines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ore__c/Ore__c.object-meta.xml
<CustomObject>
    <label>Ore</label>
    <nameField>
        <label>Ore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OreElement__c/OreElement__c.object-meta.xml
<CustomObject>
    <label>Ore Element</label>
    <nameField>
        <label>OreElement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OreElements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OreElement__c/fields/Element__c.field-meta.xml
<CustomField>
    <fullName>Element__c</fullName>
    <label>Element</label>
    <referenceTo>Element__c</referenceTo>
    <relationshipLabel>OreElements</relationshipLabel>
    <relationshipName>OreElements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OreElement__c/fields/Ore__c.field-meta.xml
<CustomField>
    <fullName>Ore__c</fullName>
    <label>Ore</label>
    <referenceTo>Ore__c</referenceTo>
    <relationshipLabel>OreElements</relationshipLabel>
    <relationshipName>OreElements</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OreReserveFinder.cls
public with sharing class OreReserveFinder {

    @AuraEnabled(cacheable=true)
    public static List<Element__c> getElements(){
        try {
            return [SELECT Id, Name FROM Element__c];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Mine__c> getAllMines(String recordId){
        try {
            System.debug('Invoked ' + recordId );
            if(recordId == 'All')
                return [SELECT Id, Name, Ore__c, Ore__r.Name, Location__latitude__s, Location__longitude__s from Mine__c];
            else{
                return [SELECT Id, Name, Ore__c, Ore__r.Name, Location__latitude__s, Location__longitude__s from Mine__c 
                WHERE Ore__c IN (SELECT Ore__c from OreElement__c WHERE Element__c = :recordId)];
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Mine__c> getNearByMines(String lat, String lon){
        try {
            return Database.query('SELECT Id, Name, Ore__c, Ore__r.Name, Location__latitude__s, Location__longitude__s from Mine__c ORDER BY DISTANCE(Location__c, GEOLOCATION(' + lat + ' , ' +lon + '), \'mi\') LIMIT 5');
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}